services:
  api:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: ./db
    container_name: botdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
      POSTGRES_DB: chatbot_db
    volumes:
      - chatbot_data:/var/lib/postgresql/data

  webapp:
    build: ./webapp
    container_name: web_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./webapp:/var/www/html
    command: ["php-fpm"]
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx_service
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - webapp


volumes:
  chatbot_data:
