services:
  api:
    build: .
    container_name: fastapi_chatbot
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: ./db
    container_name: chatbot_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
      POSTGRES_DB: chatbot_db
    volumes:
      - chatbot_data:/var/lib/postgresql/data
  
  streamlit-ui:
    build: ./streamlit_ui
    container_name: chatbot-ui
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - fastapi_chatbot
    restart: always
    volumes:
      - ./streamlit_ui:/app

volumes:
  chatbot_data:
